name: Deploy Development

on: 
  push:
    branches: 
      - preprod

jobs: 
  build:
    runs-on: ubuntu-latest 
  # Have to set to enable OIDC
    permissions:
      id-token: write 
      contents: read 

    steps: 
    - name: Trigger Deployment Pipeline
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: Bearer ${{ secrets.DEPLOY_PAT_TOKEN }}" \
          --data '{"event_type": "deploy_ecs", "client_payload": {"environment":"preprod","sha": "${{ github.sha }}"}}' \
          "https://api.github.com/repos/jdial1996/ecs-platform-app/dispatches"


