name : Push Workflow 

on: 
  push

jobs: 
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Black Check (Linting)
        run: |
          black --version
      - name: Flake8 Check (Linting)
        run: |
          flake8 --version
      - name: Docker Build
        run: |
         docker build -t platform-app ./app
      - name: Docker Image Scan 
        run: |
          echo "Scanning Image"

  