name : Push Workflow 

on: 
  push

jobs: 
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Docker Build
        run: | 
         docker build -t platform-app ./app

  