name : Push Workflow 

on: 
  push

jobs: 
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  
      - name: Install Linting Dependencies
        run: 
          pip3 install black flake8
      - name: Black Check (Linting)
        continue-on-error: true
        run: |
          black --check --diff --line-length=100 app

      - name: Flake8 Check (Linting)
        run: |
          flake8 --max-line-length=100 app 
      - name: pwd
        run : | 
          pwd 
          ls
      - name: Snyk Scan (SAST)
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Docker Build
        run: |
         docker build -t platform-app ./app
      - name: Docker Image Scan 
        run: |
          echo "Scanning Image"

  